WRMCB=function(e){var c=console;if(c&&c.log&&c.error){c.log('Error running batched script.');c.error(e);}}
;
try {
/* module-key = 'com.atlassian.confluence.plugins.confluence-sortable-tables:sortable-table-resources', location = 'js/SortableTables.js' */
define("confluence-sortable-tables/sortable-tables",["jquery","ajs","document","confluence-sortable-tables/hooks"],function(b,j,k,n){var h,l=function(a){var g=a.children("thead"),a=a.children("tbody");g.children("tr").children("th").each(function(){var a=b(this);a.removeAttr("aria-label");a&&"none"===a.attr("aria-sort")&&a.removeAttr("aria-sort")});a.removeAttr("aria-live");a.removeAttr("aria-relevant");g.attr("aria-label","Use column header buttons to sort")};return{init:function(){var a=
b("table");h=a.filter(function(){var a=b(this),e=a.find("td, th"),d=this.rows.length&&b(this.rows[0].cells),c;if("false"===a.attr("data-sortable")||-1<this.className.indexOf("tablesorter"))return!1;c=b.Event("makeSortable.SortableTables");a.trigger(c);if(c.isDefaultPrevented()||!d||0===d.length)return!1;c=0;for(var f=e.length;c<f;c++)if(a=e[c],1!=a.rowSpan||1!=a.colSpan)return!1;return b(this.rows[0]).find("table").length||d.filter("th").length!==d.length||d.hasClass("nohighlight")?!1:this.rows[1]});
a.bind("sortEnd",function(a,e){var d=b(e);l(d);if(a.target){var d=a.target,c,f,i;if(d.config&&d.config.sortList&&(c=d.config,f=c.sortList,Array.isArray(f)&&(f.length&&Array.isArray(f[0])&&1<f[0].length)&&(i=f[0][0],f=f[0][1]?"descending":"ascending",Array.isArray(c.headerList)&&c.headerList.length>=i))){c=b(c.headerList[i]).text();c=j.format("Table sorted by {0} column in {1} order",c,f);var h,m;i="a11y-notification-"+
Math.round(1E8*Math.random());b('<div class="assistive" aria-live="assertive" role="Alert" id="'+i+'"></div>').insertAfter(b(d));if(h=k.getElementById(i))b("<span>").text(c).appendTo(h),m=setTimeout(function(){h.remove();clearTimeout(m)},3E3)}}})},enable:function(){h.each(function(){if(-1<this.className.indexOf("tablesorter")||0<b(this).find("> thead").length)return!0;var a=this.removeChild(this.tBodies[0]),g=b(a.children),g=Array.prototype.shift.call(g),e=k.createDocumentFragment(),d=k.createElement("thead");
e.appendChild(d);d.appendChild(g);e.appendChild(a);this.appendChild(e)});n.beforeInitHooks().forEach(function(a){if(a&&"function"===typeof a)try{a(b.tablesorter)}catch(g){j.info("Failed to run tablesorter beforeInit hook.",g)}});b.tablesorter.addParser({id:"european-date",is:function(a,b,e){return(a=e.querySelector(".content-wrapper time"))&&!a.previousSibling&&a.parentNode&&!a.parentNode.previousSibling&&a.dateTime},format:function(a,b,e){return(a=e.querySelector("time"))?(new Date(a.dateTime)).getTime():
0},type:"numeric"});h.tablesorter({cssHeader:"sortableHeader",delayInit:!0,textExtraction:function(a){return b(a).text().trim()},tabIndex:!1,initialized:function(a){a=b(a);l(a)},headerTemplate:'<button class="headerButton">{content}</button>',cssIcon:""})},refresh:function(){this.init();this.enable()}}});require("confluence/module-exporter").safeRequire("confluence-sortable-tables/sortable-tables",function(b){require("ajs").toInit(function(){b.init();setTimeout(b.enable,100)})});
}catch(e){WRMCB(e)};